# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # specify the version you desire here
      - image: circleci/android:api-26-alpha

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx4200m
      
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
          command: sudo chmod +x ./gradlew

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
   android-build-debug:
    working_directory: ~/code
    docker:
      - image: ttfrontend/ionic-build-android:1.3.4
    steps:
      - attach_workspace:
          at: ~/code
      - run:
          name: Android debug build
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; then
                envConfig=config-prod.json yarn android:build_debug
            else
                envConfig=config-$CIRCLE_ENV_DEV.json yarn android:build_debug
            fi
      - run:
          name: Run Tests
          command: ./gradlew connectedAndroidTest
          
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      
          
          


