# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # specify the version you desire here
      - image: circleci/android:api-26-alpha

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx4200m
      TERM: dumb
      
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
          command: sudo chmod +x ./gradlew

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

test:
  override:
    # start the emulator
     - emulator -avd circleci-android22 -no-audio -no-window:
        background: true
        parallel: true
    # wait for it to have booted
     - circle-android wait-for-boot
    # unlock the emulator screen
     - sleep 30
     - adb shell input keyevent 82
    # run tests  against the emulator.
     - ./gradlew connectedAndroidTest -PdisablePreDex
          
     - store_artifacts:
          path: app/build/reports
          destination: reports
     - store_test_results:
          path: app/build/test-results
      
          
          



